### ISSUE TITLE
osd_libs compile error

### ISSUE THREAD

**Issue by rentt** [kwikius/quantracker#2] opened 2015-09-10 08:39 UTC
At the root quantracker directory and invoked "make osd_libs", the compiler gave me an error:

arm-none-eabi-g++: fatal error: cannot specify -o with -c, -S or -E with multiple files.

The library paths are correctly set in Dependencies.mk. Both tested with master and devel branch.

**Comment by kwikius** [comment] 2015-09-10 13:18
If the error message is accurate, then I suspect that this concerns DOS v Unix line endings, since the source files should each be compiled separately and should be on separate lines. 
I am assuming you are on Windows Operating System?
Do you know which make you are invoking? Is it gnu Make or mingw-make etc?
Are you invoking  make in a Unix Shell ( e.g MinGW or Cygwin) or direct from Windows?
Meantime I will try to recreate the error message and work from there

**Comment by rentt** [comment] 2015-09-10 14:25
OS information:
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Arm gcc version is:
tom@ubuntu:~/project/rentt/quantracker$ arm-none-eabi-g++ -v
Using built-in specs.
COLLECT_GCC=arm-none-eabi-g++
COLLECT_LTO_WRAPPER=/opt/gcc-arm-none-eabi-4_7-2014q2/bin/../lib/gcc/arm-none-eabi/4.7.4/lto-wrapper
Target: arm-none-eabi
.....................
gcc version 4.7.4 20140401 (release) [ARM/embedded-4_7-branch revision 209195] (GNU Tools for ARM Embedded Processors) 

The error message:
![osdlibserror](https://cloud.githubusercontent.com/assets/2141741/9790827/bad2ed18-580a-11e5-8b6f-059eb7a52c39.png)

**Comment by kwikius** [comment] 2015-09-10 14:53
From the arguments to arm-non-eabi-g++, It looks like the OPTIMISATION_LEVEL makefile variable is empty ( the minus sign after "-fno-exceptions  - c - g  - " 

In your top level Dependencies.mk file ( if it isnt defined) try adding the line :

OPTIMISATION_LEVEL := O3

and see if that fixes it. In fact I can reproduce the exact error by commenting out that variable in Dependencies.mk.

My Bad. I should check that If that is the issue I will think of a good solution, probably just to force t to -O3 if its undefined

regards
Andy

**Comment by rentt** [comment] 2015-09-10 15:02
It works after adding "OPTIMISATION_LEVEL := O3". Thank you!

**Comment by kwikius** [comment] 2015-09-10 15:08
Great :) I will add a default definition and try to correct the documentation

**Comment by kwikius** [comment] 2015-09-10 17:36
Issue should now be fixed on devel and master

**Closed by kwikius** 2015-09-10 17:36 UTC
